### PR TITLE
is this a helpful commit message?

### PR DESCRIPTION
**Pull request by ghost**
maybe we should ask  <s>@githubteacher</s> @dablum25 ..he does that 'puppet' thing... #20

### CODE REVIEW

**Comment by shall05mit** [comment]
that was a helpful commit message

**Comment by dslice25** [comment]
Submit all pull requests in triplicate to the National Pull Request Review Board :+1:

**Comment by shall05mit** [comment]
:+1:

**Comment by akalen** [comment]
:8ball:

**Pull request merged**
